<?php

function greeting_menu(){
  $items = array();
  $items['hello_friend'] = array(
    'title' => "Hello Friend!",
    'page callback' => 'say_hello',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );

  $items['goodbye'] = array(
    'title' => "Goodbye Friend!",
    'page callback' => 'say_goodbye',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );

  $items['hello_user'] = array(
    'title' => "Welcome Friend",
    'page callback' => 'say_welcome',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );

  return $items;
}

function say_welcome(){
  return '<p>Welcome to Cameron\'s Coffee, your account has been created</p>';
}

function say_hello(){
  return '<p>Hello my dear friend!</p>';
}

function say_goodbye(){
  return '<p>Goodbye my dear friend!</p>';
}

function greeting_user_login(){
  $_GET['destination'] = 'hello_friend';
}

function greeting_user_logout(){
  $_GET['destination'] = 'goodbye';
}

function greeting_user_insert(){
  $_GET['destination'] = 'hello_user';
}
