<?php

function mymodule_menu(){
    $items['path-to-ajax/%/%'] = array(
        'access arguments' => array('access content'),
        'page callback' => 'mymodule_ajax_callback',
        'page arguments' => array(1,2),
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function mymodule_ajax_callback($js, $node_id){
    $node = node_load($node_id);

    if ($js == 'nojs') {
        drupal_goto('node/' . $node->nid);
    }

    // Get the nodes array and render to html
    $build = node_view($node);
    $html = render($build);

    // Prepare ajax to insert node's html
    $commands = array();
    $commands[] = ajax_command_html('#mymodule-ajax-wrapper', $html);

    // Render the commands into JSON data format and print them to browser
    print ajax_render($commands);
    exit;
}
